const Usuario = require('../../models/Usuario');
const CodigoVerificacion = require('../../models/CodigoVerificacion');
const { Op } = require('sequelize');
const { sequelize } = require('../../db/index.js');

const confirmAccount = async (id_usuario, codigo) => {
    const transaction = await sequelize.transaction();

    try {
        console.log(`üîç Buscando c√≥digo de verificaci√≥n para usuario ID: ${id_usuario} con c√≥digo: ${codigo}`);

        const verificationCode = await CodigoVerificacion.findOne({
            where: {
                id_usuario,
                codigo,
                expiracion: { [Op.gt]: new Date() },
                usado: false
            },
            transaction
        });

        if (!verificationCode) {
            console.error('‚ùå C√≥digo de verificaci√≥n inv√°lido o expirado');
            throw new Error('C√≥digo inv√°lido o expirado');
        }

        console.log('‚úÖ C√≥digo de verificaci√≥n v√°lido, procediendo a verificar usuario.');

        // Actualizar el estado de verificaci√≥n del usuario
        const updateUser = await Usuario.update(
            { is_verified: true },
            { where: { id: id_usuario }, transaction }
        );

        console.log(`‚úÖ Usuario con ID: ${id_usuario} ha sido verificado. Filas afectadas: ${updateUser}`);

        // Marcar c√≥digo como usado en lugar de eliminarlo
        const updateCode = await CodigoVerificacion.update(
            { usado: true },
            { where: { id_usuario, codigo }, transaction }
        );

        console.log(`‚úÖ C√≥digo de verificaci√≥n marcado como usado. Filas afectadas: ${updateCode}`);

        await transaction.commit();
        return { message: 'Cuenta verificada exitosamente' };

    } catch (error) {
        await transaction.rollback();
        console.error('‚ùå Error al confirmar la cuenta:', error.message);
        throw error;
    }
};

module.exports = { confirmAccount };
